class ReadException(Exception):
    pass


class InternalError(Exception):
    pass
